### ISSUE TITLE
how to hardcode an external .csv file to ofxCsv object

### ISSUE THREAD

**Issue by moebiussurfing** [paulvollmer/ofxCsv#29]
hey @paulvollmer , thanks for your addon, it's being very helpful!

I am using it to make a time playlist event trigger. I am loading an external file using a space " " as separator and it's working really fine.

Now, after having the file finished, I want to hardcode all the file into the OF ofApp, just to hide the file for unwanted modifications.

my file.csv looks like:
```
TIME DEV_TYPE ID COMMAND FADE_TIME
2000 RELAY 3 ON
2500 DMX 4 FADE_IN_PAUSE_OUT 2000
3000 RELAY 4 ON
3400 RELAY 8 ON
```

I am tring to joint all the lines into a string or a vector of string and then to try to use your load function to load the string... but I am not having success! :)

My idea is to not have to use all the addRow, addString methods manually, and just copy paste all lines  from the external text editor to OF with something like that:
string myCSVfullString = "TIME DEV_TYPE ID COMMAND FADE_TIME\n2000 RELAY 3 ON\n ...";

I am trying with your 

`load(vector<string> rows)`

method with a push_back for any line too, also trying with commas besides spaces, but without success neither...

any help? or that has not sense for you?
Thanks

**Comment by moebiussurfing** [comment]
ok. sorry, now is understand the example better. should be something like that:

ofxCsvRow row1("TIME DEV_TYPE ID COMMAND FADE_TIME", " ");
ofxCsvRow row2("2000 RELAY 3 ON", " ");
ofxCsvRow row3("2500 DMX 4 FADE_IN_PAUSE_OUT 2000", " ");
csv.addRow(row1);
csv.addRow(row2);
csv.addRow(row3);

that's rigth? do you see any other faster way around?

**Comment by paulvollmer** [comment]
@moebiussurfing i had no time to answer questons for that project the last long time.

why you're not creating a 2 dimensional string array to store your constant data. then you don't need to do any kind of processing.
