### ISSUE TITLE
Openframeworks 0.10 compile Errors 

### ISSUE THREAD

**Issue by awilkie1** [paulvollmer/ofxCsv#32]
Seems to be compiling issues with 0.10 latest version. withing the file ofxCsvRow.h

'string'; did you mean 'std::string'
'vector'; did you mean 'std::vector'

**Comment by maro525** [comment]
adding `using namespace std;`  to ofxCsvRow.h 

it would work

**Comment by maro525** [comment]
and also, needs to change MAX(**, **) to max(**, **) in both ofxCsvRow.cpp and ofxCsv.cpp

**Comment by paulvollmer** [comment]
hello @maro525 

at the moment i have no time to maintain the `ofxCsv` addon. if you have the fix for this error and time to send a PR i can merge it to the master.

thank you guys.

**Comment by paulvollmer** [comment]
PR is #35
